
#server:
 # ssl:
  ## key-store-password: 123456
    #key-store: classpath:ssl/keystore.p12
    #key-store-type: PKCS12
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  datasource:
    # jdbc:mysql://rm-wz9qa53m3xbn8hiujo.mysql.rds.aliyuncs.com:3306/st_agent?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    url: ENC(DMcX/k3HFSGf+LSFoUmTxsKEmUouODHx+gfaS0rFvsXbNqChSkO8TRNesxzWdOYEV6ZHRWJWhOJ2LafzYGWwFpgNMdHZntvCizkMdv7YfKfNLNjCnRBBgUfjlofETOHHz34m3J3zyG/aUaTgqxVEuZAtc9ie/L5m4s4rmbGCm8/rRTY826QgQnaNJ5zWC28D)
    #url: jdbc:mysql://rm-wz9qa53m3xbn8hiujo.mysql.rds.aliyuncs.com:3306/st_agent?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    # st_test
    #username: st_test
    username: ENC(+MQxFVm4kF2N1+veJ9A9GQ==)
    # @stTest!1103#St$
    #password: '@stTest!1103#St$'
    password: ENC(wJ5+6HyHrU+FXgcOL2AXNcPRuDnxYdSvPXhiaK14H0U=)
    continue-on-error: true
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filters: stat,wall,log4j2
  # redis
  redis:
    host: 39.107.90.67
    port: 6379
    password: Mm123456
  # rabbitmq
  rabbitmq:
    host: 39.107.90.67
    username: admin
    password: Mm123456
  #data:
    # elasticsearch
    #elasticsearch:
     # cluster-nodes: 39.107.90.67:9200
      #repositories:
       # enabled: true
inv:
  test: 123123
jasypt:
  encryptor:
    password: demo

